Deze code kan je doorlopen om van de nc bestanden van biooracle een dataset te maken met de juiste locaties zoals onze oorspronkelijke dataset

In [1]:
import pandas as pd
import xarray as xr
import glob
import numpy as np

In [2]:
df1 = pd.read_csv(r"C:\Emma\2. Bestanden\1. UGent\3e bachelor (2025-2026)\2e semester\Bachelorproef\Programmeergedeelte\Bachelorproef\Data\Diversity_data_with_biooracle_2010.csv")
df1.columns
df1.head()

,marine_species_richness,PD,co1_genetic_diversity_mean,long_deg,lat_deg,chl_max,chl_mean,chl_min,clt_max,clt_mean,...,terrain_characteristics_bea_min,terrain_characteristics_rug,terrain_characteristics_slope,terrain_characteristics_topo,T_ltmax,T_ltmin,T_max,T_mean,T_min,T_range
0,44,11.830844,0.007171,-171.74579,-71.23536,1.987486,0.264222,0.015311,0.993542,0.681597,...,-3883.0,66.347260,0.933108,6.854279,-0.711044,-1.904281,-0.127859,-1.602750,-1.977225,1.849366
1,43,11.830844,0.007171,-167.88679,-71.23536,2.205368,0.278952,0.015232,0.961121,0.693978,...,-4084.0,21.055542,0.320794,-12.930603,-0.847708,-1.925544,-0.017505,-1.620118,-2.000000,1.988636
2,44,12.650381,0.007499,-164.02779,-71.23536,1.891105,0.270836,0.015052,0.960210,0.698352,...,-4153.0,14.489563,0.228825,5.524109,-0.521772,-1.923338,0.125601,-1.582915,-2.000000,2.137620
3,44,12.650381,0.007499,-160.16879,-71.23536,1.963815,0.293940,0.015424,0.962838,0.693123,...,-4303.0,4.413208,0.081748,1.760254,-0.558407,-1.909406,-0.032617,-1.579760,-1.976150,1.943533
4,45,12.650381,0.007499,-156.30979,-71.23536,1.956123,0.298378,0.015726,0.969080,0.688964,...,-4341.0,10.302124,0.234018,-0.892456,-0.570859,-1.906482,-0.000029,-1.570748,-2.000000,2.001978

maak een dataset aan met enkel de locaties (dit hebben we straks nodig)

In [3]:
df_locations = df1[["long_deg", "lat_deg"]]
df_locations.head(10)

    long_deg   lat_deg
0 -171.74579 -71.23536
1 -167.88679 -71.23536
2 -164.02779 -71.23536
3 -160.16879 -71.23536
4 -156.30979 -71.23536
5 -152.45079 -71.23536
6 -148.59179 -71.23536
7 -144.73279 -71.23536
8 -140.87379 -71.23536
9  -59.83479 -71.23536

In [4]:
df2 = pd.read_csv(r"C:\Emma\2. Bestanden\1. UGent\3e bachelor (2025-2026)\2e semester\Bachelorproef\Programmeergedeelte\Bachelorproef\Data\Diversity_data_with_env.csv")
df2.head()

,grid_id,long,lat,marine_species_richness,PD,co1_genetic_diversity_mean,long_deg,lat_deg,long_dd,lat_dd,...,Shelf,Slope,Abyssal,TidalRange,Coral,Estuary,Seamount,MPA,matched_CenterLong,matched_CenterLat
0,1,-17174579,-7123536,44,11.830844,0.007171,-171.74579,-71.23536,-171.74579,-71.23536,...,0.0,730.228795,263.361205,-9999.0,0.0,0.0,0,NaN,-171.75,-71.25
1,2,-16788679,-7123536,43,11.830844,0.007171,-167.88679,-71.23536,-167.88679,-71.23536,...,0.0,0.000000,993.590000,-9999.0,0.0,0.0,0,NaN,-167.75,-71.25
2,3,-16402779,-7123536,44,12.650381,0.007499,-164.02779,-71.23536,-164.02779,-71.23536,...,0.0,0.000000,993.590000,-9999.0,0.0,0.0,0,NaN,-164.25,-71.25
3,4,-16016879,-7123536,44,12.650381,0.007499,-160.16879,-71.23536,-160.16879,-71.23536,...,0.0,0.000000,993.590000,-9999.0,0.0,0.0,0,NaN,-160.25,-71.25
4,5,-15630979,-7123536,45,12.650381,0.007499,-156.30979,-71.23536,-156.30979,-71.23536,...,0.0,0.000000,993.590000,-9999.0,0.0,0.0,0,NaN,-156.25,-71.25

Verzamel al je nc bestanden in een map zoals de map Data.
Ik zou per biodiversiteitsmaat een andere naam aan de map geven (mss ncPD, ncGD en ncSR?)

In [5]:
files = glob.glob(r"C:\Emma\2. Bestanden\1. UGent\3e bachelor (2025-2026)\2e semester\Bachelorproef\Programmeergedeelte\Bachelorproef\ncSR\*.nc")

Van alle aparte nc bestandjes 1 geheeld maken

In [6]:
datasets = [xr.open_dataset(f) for f in files]
ds = xr.merge(datasets)

print(ds)

<xarray.Dataset> Size: 2GB
Dimensions:      (time: 1, latitude: 3600, longitude: 7200)
Coordinates:
  * time         (time) datetime64[ns] 8B 2050-01-01
  * latitude     (latitude) float32 14kB -89.97 -89.93 -89.88 ... 89.93 89.97
  * longitude    (longitude) float32 29kB -180.0 -179.9 -179.9 ... 179.9 180.0
Data variables:
    clt_mean     (time, latitude, longitude) float64 207MB ...
    dfe_mean     (time, latitude, longitude) float64 207MB ...
    mlotst_mean  (time, latitude, longitude) float64 207MB ...
    o2_mean      (time, latitude, longitude) float64 207MB ...
    phyc_mean    (time, latitude, longitude) float64 207MB ...
    ph_mean      (time, latitude, longitude) float64 207MB ...
    po4_mean     (time, latitude, longitude) float64 207MB ...
    siconc_mean  (time, latitude, longitude) float64 207MB ...
    so_mean      (time, latitude, longitude) float64 207MB ...
    sws_mean     (time, latitude, longitude) float64 207MB ...
    tas_mean     (time, latitude, longitude) float64 207MB ...
    thetao_mean  (time, latitude, longitude) float64 207MB ...
Attributes: (12/40)
    cdm_data_type:                             Grid
    comment:                                   Uses attributes recommended by...
    Conventions:                               CF-1.5
    creator_name:                              Bio-Oracle consortium: https:/...
    creator_url:                               https://www.bio-oracle.org
    Easternmost_Easting:                       179.975
    ...                                        ...
    standard_name_vocabulary:                  CF Standard Name Table v70
    summary:                                   Uses attributes recommended by...
    time_coverage_end:                         2050-01-01T00:00:00Z
    time_coverage_start:                       2050-01-01T00:00:00Z
    title:                                     Bio-Oracle TotalCloudFraction ...
    Westernmost_Easting:                       -179.975

De dataset omvormen tot een dataframe waarmee je kan verder werken om aanpassingen aan te brengen

In [7]:
df = ds.to_dataframe().reset_index()

In [8]:
len(df)  # is nog veel te lang dus veel locaties moeten nog wegvallen => komt straks

25920000

In [9]:
df.head()    # je ziet dat longitude en latitude de variabelen zijn maar we hebben long_deg en lat_deg nodig

,time,latitude,longitude,clt_mean,dfe_mean,mlotst_mean,o2_mean,phyc_mean,ph_mean,po4_mean,siconc_mean,so_mean,sws_mean,tas_mean,thetao_mean
0,2050-01-01,-89.974998,-179.975006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2050-01-01,-89.974998,-179.925003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2050-01-01,-89.974998,-179.875000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2050-01-01,-89.974998,-179.824997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2050-01-01,-89.974998,-179.774994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df.rename(columns={"longitude": "long_deg", "latitude": "lat_deg"})

Je moet long_deg en lat_deg afronden tot op 5 cijfers na de komma anders zit je met andere komma getallen dan bij de oorspronkelijke dataset

In [11]:
print(df[["lat_deg", "long_deg"]].dtypes)
df["lat_deg"] = df["lat_deg"].astype("float64").round(5)
df["long_deg"] = df["long_deg"].astype("float64").round(5)
print(df[["lat_deg", "long_deg"]].head())

lat_deg     float32
long_deg    float32
dtype: object
   lat_deg   long_deg
0  -89.975 -179.97501
1  -89.975 -179.92500
2  -89.975 -179.87500
3  -89.975 -179.82500
4  -89.975 -179.77499

De volgende code is om de locaties te laten kloppen zoals in de oorspronkelijke dataset

In [12]:
# functie om dichtstbijzijnde waarde te vinden
def nearest(array, values):
    """
    array: 1D array van rasterwaarden (lat of long)
    values: array van gewenste waarden
    return: voor elke waarde in values de dichtstbijzijnde in array
    """
    array = np.array(array)
    values = np.array(values)
    idx = np.abs(array[:, None] - values).argmin(axis=0)
    return array[idx]

# vind dichtstbijzijnde lat/lon
df_locations["lat_match"] = nearest(df["lat_deg"].unique(), df_locations["lat_deg"])
df_locations["long_match"] = nearest(df["long_deg"].unique(), df_locations["long_deg"])

# merge op de “nearest” kolommen
df_subset = df.merge(
    df_locations,
    left_on=["lat_deg", "long_deg"],
    right_on=["lat_match", "long_match"],
    how="inner"
)

C:\Users\aluwe\AppData\Local\Temp\ipykernel_17872\4132841367.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_locations["lat_match"] = nearest(df["lat_deg"].unique(), df_locations["lat_deg"])
C:\Users\aluwe\AppData\Local\Temp\ipykernel_17872\4132841367.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_locations["long_match"] = nearest(df["long_deg"].unique(), df_locations["long_deg"])

In [13]:
df_subset.head()  #je ziet dat long_deg_y en lat_deg_y exact overeenkomen met de originele dataset => al de rest
# van long en lat variabelen kan je verwijderen

,time,lat_deg_x,long_deg_x,clt_mean,dfe_mean,mlotst_mean,o2_mean,phyc_mean,ph_mean,po4_mean,siconc_mean,so_mean,sws_mean,tas_mean,thetao_mean,long_deg_y,lat_deg_y,lat_match,long_match
0,2050-01-01,-71.225,-171.72501,0.689485,0.000391,61.532763,314.002378,1.237505,7.970945,2.152274,0.729408,33.931405,0.049441,-12.110121,-1.641139,-171.74579,-71.23536,-71.225,-171.72501
1,2050-01-01,-71.225,-167.87500,0.700666,0.000376,63.236088,315.845510,1.337427,7.972867,2.166582,0.722381,33.946644,0.029165,-11.803244,-1.652577,-167.88679,-71.23536,-71.225,-167.87500
2,2050-01-01,-71.225,-164.02499,0.703526,0.000368,63.562959,315.316479,1.259565,7.973096,2.168482,0.690216,33.945152,0.019922,-11.386030,-1.605413,-164.02779,-71.23536,-71.225,-164.02499
3,2050-01-01,-71.225,-160.17500,0.697370,0.000348,59.205664,318.284476,1.335023,7.976109,2.159415,0.696709,33.912422,0.016173,-10.963306,-1.617962,-160.16879,-71.23536,-71.225,-160.17500
4,2050-01-01,-71.225,-156.32500,0.692536,0.000343,60.567262,317.223787,1.358980,7.975836,2.158386,0.697316,33.883653,0.013395,-10.523488,-1.626628,-156.30979,-71.23536,-71.225,-156.32500

In [14]:
df_subset = df_subset.drop(["lat_match","long_match", "long_deg_x", "lat_deg_x", "time"], axis = 1)
df_subset.head()

,clt_mean,dfe_mean,mlotst_mean,o2_mean,phyc_mean,ph_mean,po4_mean,siconc_mean,so_mean,sws_mean,tas_mean,thetao_mean,long_deg_y,lat_deg_y
0,0.689485,0.000391,61.532763,314.002378,1.237505,7.970945,2.152274,0.729408,33.931405,0.049441,-12.110121,-1.641139,-171.74579,-71.23536
1,0.700666,0.000376,63.236088,315.845510,1.337427,7.972867,2.166582,0.722381,33.946644,0.029165,-11.803244,-1.652577,-167.88679,-71.23536
2,0.703526,0.000368,63.562959,315.316479,1.259565,7.973096,2.168482,0.690216,33.945152,0.019922,-11.386030,-1.605413,-164.02779,-71.23536
3,0.697370,0.000348,59.205664,318.284476,1.335023,7.976109,2.159415,0.696709,33.912422,0.016173,-10.963306,-1.617962,-160.16879,-71.23536
4,0.692536,0.000343,60.567262,317.223787,1.358980,7.975836,2.158386,0.697316,33.883653,0.013395,-10.523488,-1.626628,-156.30979,-71.23536

In [15]:
len(df_subset)  # lengte komt exact overeen met oorspronkelijke dataset

2452

In [16]:
df_subset = df_subset.rename(columns={"long_deg_y": "long_deg", "lat_deg_y": "lat_deg"})
df_subset.head()

,clt_mean,dfe_mean,mlotst_mean,o2_mean,phyc_mean,ph_mean,po4_mean,siconc_mean,so_mean,sws_mean,tas_mean,thetao_mean,long_deg,lat_deg
0,0.689485,0.000391,61.532763,314.002378,1.237505,7.970945,2.152274,0.729408,33.931405,0.049441,-12.110121,-1.641139,-171.74579,-71.23536
1,0.700666,0.000376,63.236088,315.845510,1.337427,7.972867,2.166582,0.722381,33.946644,0.029165,-11.803244,-1.652577,-167.88679,-71.23536
2,0.703526,0.000368,63.562959,315.316479,1.259565,7.973096,2.168482,0.690216,33.945152,0.019922,-11.386030,-1.605413,-164.02779,-71.23536
3,0.697370,0.000348,59.205664,318.284476,1.335023,7.976109,2.159415,0.696709,33.912422,0.016173,-10.963306,-1.617962,-160.16879,-71.23536
4,0.692536,0.000343,60.567262,317.223787,1.358980,7.975836,2.158386,0.697316,33.883653,0.013395,-10.523488,-1.626628,-156.30979,-71.23536

De volgende 2 stukjes code moeten true terug geven (dit is ter controle) wel belangrijk!!!!

In [17]:
(df1['lat_deg'] == df_subset['lat_deg']).all()  # True als alle rijen exact overeenkomen

np.True_

In [18]:
(df1['long_deg'] == df_subset['long_deg']).all() # True als alle rijden exact overeenkomen

np.True_

In [19]:
df_subset

,clt_mean,dfe_mean,mlotst_mean,o2_mean,phyc_mean,ph_mean,po4_mean,siconc_mean,so_mean,sws_mean,tas_mean,thetao_mean,long_deg,lat_deg
0,0.689485,0.000391,61.532763,314.002378,1.237505,7.970945,2.152274,0.729408,33.931405,0.049441,-12.110121,-1.641139,-171.74579,-71.23536
1,0.700666,0.000376,63.236088,315.845510,1.337427,7.972867,2.166582,0.722381,33.946644,0.029165,-11.803244,-1.652577,-167.88679,-71.23536
2,0.703526,0.000368,63.562959,315.316479,1.259565,7.973096,2.168482,0.690216,33.945152,0.019922,-11.386030,-1.605413,-164.02779,-71.23536
3,0.697370,0.000348,59.205664,318.284476,1.335023,7.976109,2.159415,0.696709,33.912422,0.016173,-10.963306,-1.617962,-160.16879,-71.23536
4,0.692536,0.000343,60.567262,317.223787,1.358980,7.975836,2.158386,0.697316,33.883653,0.013395,-10.523488,-1.626628,-156.30979,-71.23536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,0.695511,0.005797,10.720185,0.000000,0.000000,7.883154,0.000000,0.632040,22.276497,0.004238,0.000000,0.500560,156.26921,71.54764
2448,0.733831,0.004956,13.416158,0.000000,0.000000,7.910328,0.000000,0.636376,24.158264,0.011577,0.000000,0.204842,160.12821,71.54764
2449,0.736944,0.003522,15.198769,0.000000,0.000000,7.936712,0.000000,0.636173,25.786871,0.008452,0.000000,-0.020064,163.98721,71.54764
2450,0.730593,0.002479,16.403816,0.000000,0.000000,7.948699,0.000000,0.637944,26.612541,0.006839,0.000000,-0.225177,167.84621,71.54764
2451,0.739369,0.001607,15.467311,0.000000,0.000000,7.989900,0.000000,0.624054,28.318791,0.009510,0.000000,-0.338453,171.70521,71.54764

De volgende code is afhankelijk van welke variabelen je in je model steekt (dus niet exact kopiëren)

In [20]:
df_subset = df_subset.rename(columns={
    "so_mean": "salinity_mean",
    "sws_mean": "currentvelocity_mean",
    "thetao_mean": "T_mean",
    "siconc_mean": "si_mean"
})
df_subset.columns

Index(['clt_mean', 'dfe_mean', 'mlotst_mean', 'o2_mean', 'phyc_mean',
       'ph_mean', 'po4_mean', 'si_mean', 'salinity_mean',
       'currentvelocity_mean', 'tas_mean', 'T_mean', 'long_deg', 'lat_deg'],
      dtype='object')

In [21]:
df_subset.head()

,clt_mean,dfe_mean,mlotst_mean,o2_mean,phyc_mean,ph_mean,po4_mean,si_mean,salinity_mean,currentvelocity_mean,tas_mean,T_mean,long_deg,lat_deg
0,0.689485,0.000391,61.532763,314.002378,1.237505,7.970945,2.152274,0.729408,33.931405,0.049441,-12.110121,-1.641139,-171.74579,-71.23536
1,0.700666,0.000376,63.236088,315.845510,1.337427,7.972867,2.166582,0.722381,33.946644,0.029165,-11.803244,-1.652577,-167.88679,-71.23536
2,0.703526,0.000368,63.562959,315.316479,1.259565,7.973096,2.168482,0.690216,33.945152,0.019922,-11.386030,-1.605413,-164.02779,-71.23536
3,0.697370,0.000348,59.205664,318.284476,1.335023,7.976109,2.159415,0.696709,33.912422,0.016173,-10.963306,-1.617962,-160.16879,-71.23536
4,0.692536,0.000343,60.567262,317.223787,1.358980,7.975836,2.158386,0.697316,33.883653,0.013395,-10.523488,-1.626628,-156.30979,-71.23536

In [22]:
df2 = pd.read_csv(r"C:\Emma\2. Bestanden\1. UGent\3e bachelor (2025-2026)\2e semester\Bachelorproef\Programmeergedeelte\Bachelorproef\Data\Diversity_data_with_env.csv")
df2.head()

,grid_id,long,lat,marine_species_richness,PD,co1_genetic_diversity_mean,long_deg,lat_deg,long_dd,lat_dd,...,Shelf,Slope,Abyssal,TidalRange,Coral,Estuary,Seamount,MPA,matched_CenterLong,matched_CenterLat
0,1,-17174579,-7123536,44,11.830844,0.007171,-171.74579,-71.23536,-171.74579,-71.23536,...,0.0,730.228795,263.361205,-9999.0,0.0,0.0,0,NaN,-171.75,-71.25
1,2,-16788679,-7123536,43,11.830844,0.007171,-167.88679,-71.23536,-167.88679,-71.23536,...,0.0,0.000000,993.590000,-9999.0,0.0,0.0,0,NaN,-167.75,-71.25
2,3,-16402779,-7123536,44,12.650381,0.007499,-164.02779,-71.23536,-164.02779,-71.23536,...,0.0,0.000000,993.590000,-9999.0,0.0,0.0,0,NaN,-164.25,-71.25
3,4,-16016879,-7123536,44,12.650381,0.007499,-160.16879,-71.23536,-160.16879,-71.23536,...,0.0,0.000000,993.590000,-9999.0,0.0,0.0,0,NaN,-160.25,-71.25
4,5,-15630979,-7123536,45,12.650381,0.007499,-156.30979,-71.23536,-156.30979,-71.23536,...,0.0,0.000000,993.590000,-9999.0,0.0,0.0,0,NaN,-156.25,-71.25

Nog de variabelen van env toevoegen die je ook nodig hebt voor in je model

In [23]:
df_merged = df_subset.merge(
    df2[['long_deg', 'lat_deg', 'DepthMean', 'LandDist', 'Slope']],
    on=['long_deg', 'lat_deg'],
    how='left'
)
df_merged.head()

,clt_mean,dfe_mean,mlotst_mean,o2_mean,phyc_mean,ph_mean,po4_mean,si_mean,salinity_mean,currentvelocity_mean,tas_mean,T_mean,long_deg,lat_deg,DepthMean,LandDist,Slope
0,0.689485,0.000391,61.532763,314.002378,1.237505,7.970945,2.152274,0.729408,33.931405,0.049441,-12.110121,-1.641139,-171.74579,-71.23536,3998,636,730.228795
1,0.700666,0.000376,63.236088,315.845510,1.337427,7.972867,2.166582,0.722381,33.946644,0.029165,-11.803244,-1.652577,-167.88679,-71.23536,4079,742,0.000000
2,0.703526,0.000368,63.562959,315.316479,1.259565,7.973096,2.168482,0.690216,33.945152,0.019922,-11.386030,-1.605413,-164.02779,-71.23536,4185,708,0.000000
3,0.697370,0.000348,59.205664,318.284476,1.335023,7.976109,2.159415,0.696709,33.912422,0.016173,-10.963306,-1.617962,-160.16879,-71.23536,4231,661,0.000000
4,0.692536,0.000343,60.567262,317.223787,1.358980,7.975836,2.158386,0.697316,33.883653,0.013395,-10.523488,-1.626628,-156.30979,-71.23536,4322,608,0.000000

In [24]:
df_merged_vol = df_merged.merge(
    df1[['kdpar_mean', 'par_mean', 'terrain_characteristics_rug','terrain_characteristics_slope', 'long_deg', 'lat_deg' ]],
    on=['long_deg', 'lat_deg'],
    how='left'
)

df_merged_vol.head()

,clt_mean,dfe_mean,mlotst_mean,o2_mean,phyc_mean,ph_mean,po4_mean,si_mean,salinity_mean,currentvelocity_mean,...,T_mean,long_deg,lat_deg,DepthMean,LandDist,Slope,kdpar_mean,par_mean,terrain_characteristics_rug,terrain_characteristics_slope
0,0.689485,0.000391,61.532763,314.002378,1.237505,7.970945,2.152274,0.729408,33.931405,0.049441,...,-1.641139,-171.74579,-71.23536,3998,636,730.228795,0.060146,37.450932,66.347260,0.933108
1,0.700666,0.000376,63.236088,315.845510,1.337427,7.972867,2.166582,0.722381,33.946644,0.029165,...,-1.652577,-167.88679,-71.23536,4079,742,0.000000,0.062998,29.998841,21.055542,0.320794
2,0.703526,0.000368,63.562959,315.316479,1.259565,7.973096,2.168482,0.690216,33.945152,0.019922,...,-1.605413,-164.02779,-71.23536,4185,708,0.000000,0.072465,32.604841,14.489563,0.228825
3,0.697370,0.000348,59.205664,318.284476,1.335023,7.976109,2.159415,0.696709,33.912422,0.016173,...,-1.617962,-160.16879,-71.23536,4231,661,0.000000,0.067391,31.006588,4.413208,0.081748
4,0.692536,0.000343,60.567262,317.223787,1.358980,7.975836,2.158386,0.697316,33.883653,0.013395,...,-1.626628,-156.30979,-71.23536,4322,608,0.000000,0.066070,33.850906,10.302124,0.234018

Sla je dataset op als csv bestand dan kan je dit gebruiken in je ander documentje met je model

In [25]:
df_merged_vol.to_csv("SR_2050-60_SSP119.csv")